declare -A dir=(
    [CROSS-submission]="Code-based_Signatures/CROSS-submission2/Additional_Implementations/KAT_Generation"
    [Enhanced_pqsigRM-submission]="Code-based_Signatures/Enhanced_pqsigRM-submission/Reference_Implementation"
    [FuLeeca-submission]="Code-based_Signatures/FuLeeca-submission/Submission_Package/Reference_Implementation"
    [LESS-submission]="Code-based_Signatures/LESS-submission/Submission_LESS/Additional_Implementations/KAT_Generation"
    [MEDS-submission]="Code-based_Signatures/MEDS-submission/MEDS-2023/Reference_Implementation"
    [Wave-submission]="Code-based_Signatures/Wave-submission/WaveR1_1/Reference_implementation"
    [sqisign-submission]="Isogeny_Signatures/sqisign-submission/Reference_Implementation"
    [EagleSign-submission]="Lattice-based_Signatures/EagleSign-submission/EagleSign/Specifications_and_Supporting_Documentation/Reference_Implementation"
    [EHTv3v4-Submission]="Lattice-based_Signatures/EHTv3v4-Submission/EHTv3v4/Reference_Implementation/crypto_sign"
    [HAETAE-submission]="Lattice-based_Signatures/HAETAE-submission/Reference_Implementation"
    [hawk-submission]="Lattice-based_Signatures/hawk-submission/hawk-submission/Reference_Implementation"
    [HuFu-submission-noKATs]="Lattice-based_Signatures/HuFu-submission-noKATs/HuFu-noKATs/HuFu/Reference_Implementation/crypto_sign"
    [raccoon-submission]="Lattice-based_Signatures/raccoon-submission/Raccoon/Reference_Implementation"
    [squirrels-submission-noKATs]="Lattice-based_Signatures/squirrels-submission-noKATs/Reference_Implementation"
    [Biscuit-submission]="MPC-in-the-Head_Signatures/Biscuit-submission/Biscuit/Reference_Implementation"
    [MIRA-submission]="MPC-in-the-Head_Signatures/MIRA-submission/MIRA/Reference_Implementation"
    [mirith-submission]="MPC-in-the-Head_Signatures/mirith-submission/mirith_nist_submission-main/Reference_Implementation"
    [mqom-submission]="MPC-in-the-Head_Signatures/mqom-submission/submission_package/Reference_Implementation"
    [Perk-submission]="MPC-in-the-Head_Signatures/Perk-submission/perk/Reference_Implementation"
    [ryde-submission]="MPC-in-the-Head_Signatures/ryde-submission/ryde/Reference_Implementation"
    [SDitH-submission]="MPC-in-the-Head_Signatures/SDitH-submission/submission_package/Reference_Implementation"
    [3WISE-submission-noKATs]="Multivariate_Signatures/3WISE-submission-noKATs/3WISE-20230531/Reference_Implementation"
    [DME-SIGN-submission]="Multivariate_Signatures/DME-SIGN-submission/DME-SIGN_nist-pqc-2023"
    [HPPC-submission]="Multivariate_Signatures/HPPC-submission/HPPC-20230710/Reference_Implementation"
    [mayo-submission]="Multivariate_Signatures/mayo-submission/Reference_Implementation"
    [PROV-submission-noKAT]="Multivariate_Signatures/PROV-submission-noKAT/PROV_submission/Reference_Implementation"
    [QR-UOV-submission]="Multivariate_Signatures/QR-UOV-submission/QR_UOV - no IVs/QR_UOV/Reference_Implementation"
    [SNOVAnoKATs-submission]="Multivariate_Signatures/SNOVAnoKATs-submission/SNOVA/Reference_Implementation"
    [TUOV-submission]="Multivariate_Signatures/TUOV-submission/TUOV/Reference_Implementation"
    [UOV-submission]="Multivariate_Signatures/UOV-submission/UOV (1)/UOV/Reference_Implementation"
    [vox-submission]="Multivariate_Signatures/vox-submission/Reference_Implementation/vox_sign"
    [ALTEQnoKATs-submission]="Other_Signatures/ALTEQnoKATs-submission/ALTEQ/KAT_copy_5"
    [eMLE2.0-submission]="Other_Signatures/eMLE2.0-submission/eMLE2.0/Reference_Implementation/crypto_sign"
    [KAZ-SIGN]="Other_Signatures/KAZ-SIGN-CODES-v1.6/KAZ-SIGN-CODES/KAZ-SIGN-LINUX/Reference_Implementation"
    [Preon-submission-noKAT]="Other_Signatures/Preon-submission-noKAT/Preon_submission/Reference_Implementation"
    [Xifrat-submission]="Other_Signatures/Xifrat-submission/Xifrat-NIST-Submission-2023-05-16/Reference_Implementation"
    [AIMer-submission]="Symmetric-based_Signatures/AIMer-submission/AIMer-NIST-submission/AIMer_submission/Reference_Implementation"
    [Ascon-Sign-Submission]="Symmetric-based_Signatures/Ascon-Sign-Submission/Ascon_sign_full_7-11/Reference_Implementation"
    [FAEST-submission]="Symmetric-based_Signatures/FAEST-submission/nist_submission/Reference_Implementation"
    [SPHINCS-ALPHA-submission]="Symmetric-based_Signatures/SPHINCS-ALPHA-submission/SPHINCS-ALPHA/Reference_Implementation"
    [Dilithium-Round3]="Selected_Signatures/Dilithium-Round3/Dilithium/dilithium/Reference_Implementation/crypto_sign"
    [Falcon-Round3]="Selected_Signatures/Falcon-Round3/Falcon/falcon-round3/Reference_Implementation"
    [SPHINCS-Round3]="Selected_Signatures/SPHINCS-Round3/NIST-PQ-Submission-SPHINCS-20201001/Reference_Implementation/crypto_sign"
)

declare -a keys=(
    "CROSS-submission"
    "Enhanced_pqsigRM-submission"
    "FuLeeca-submission"
    "LESS-submission"
    "MEDS-submission"
    "Wave-submission"
    "sqisign-submission"
    "EagleSign-submission"
    "EHTv3v4-Submission"
    "HAETAE-submission"
    "hawk-submission"
    "HuFu-submission-noKATs"
    "raccoon-submission"
    "squirrels-submission-noKATs"
    "Biscuit-submission"
    "MIRA-submission"
    "mirith-submission"
    "mqom-submission"
    "Perk-submission"
    "ryde-submission"
    "SDitH-submission"
    "3WISE-submission-noKATs"
    "DME-SIGN-submission"
    "HPPC-submission"
    "mayo-submission"
    "PROV-submission-noKAT"
    "QR-UOV-submission"
    "SNOVAnoKATs-submission"
    "TUOV-submission"
    "UOV-submission"
    "vox-submission"
    "ALTEQnoKATs-submission"
    "eMLE2.0-submission"
    "KAZ-SIGN"
    "Preon-submission-noKAT"
    "Xifrat-submission"
    "AIMer-submission"
    "Ascon-Sign-Submission"
    "FAEST-submission"
    "SPHINCS-ALPHA-submission"
    "Dilithium-Round3"
    "Falcon-Round3"
    "SPHINCS-Round3"
    )

i=1
for key in "${keys[@]}"; do
    echo
    echo "Scheme ${i}"
    echo "Executing ${key}..."
    cd "HOME/Project/"
    cd "${dir[$key]}"
    chmod +x execution.sh
    ./execution.sh
    ((i=i+1))
    cd
done